### ISSUE TITLE
USB Debug off

### ISSUE THREAD

**Issue by No-013** [Maxpnl/Xiaomi-Unlocker-Fake-Fastboot#3]
I don't suppose you know of a way to circumvent having USB debugging turned off. My device is hard bricked, locked and unable to access recovery mode. I'm just trying to reflash the original ROM onto the device, but every method I've found wont work in these circumstances. 

Thanks for your time either way.

**Comment by Maxpnl** [comment]
Sorry, I don't know how you could solve this, maybe try asking this question in MIUI forum and you could get lucky
